### ISSUE TITLE
Errors when bootstrapping dobi

### ISSUE THREAD

**Issue by deinspanjer** [dnephin/dobi#12]
Following the instructions on https://dnephin.github.io/dobi/install.html to clone the repo and run the docker command to generate binaries, I get a bunch of errors.  I'm running with Docker for Mac v 1.12.1-beta24.1.

The very first sign of trouble is a warn:

> Status: Downloaded newer image for dnephin/dobi:0.5
> [WARN] Failed to load auth config: open /.dockercfg: no such file or directory
> [image:build builder] dobi-dev Building

I'm not sure why it would be looking for a .dockercfg at all, especially in the root file system.  My auth config is in the standard location, ~/.docker/config.json

It then plugs along for a while seemingly okay until:
> Step 9 : ENV CGO_ENABLED 0

It downloads about 20 dependencies fine, up to:
> [INFO]	--> Fetching updates for github.com/docker/go-units.

and then it starts erroring for most the rest of them:

> [WARN]	Unable to checkout github.com/inconshreveable/mousetrap
> [ERROR]	Update failed for github.com/inconshreveable/mousetrap: Unable to get repository
> [WARN]	Unable to checkout github.com/docker/engine-api
> [ERROR]	Update failed for github.com/docker/engine-api: Unable to get repository
> [WARN]	Unable to checkout github.com/Sirupsen/logrus
> [ERROR]	Update failed for github.com/Sirupsen/logrus: Unable to get repository
> [WARN]	Unable to checkout github.com/fsouza/go-dockerclient
> [INFO]	--> Fetching updates for gopkg.in/yaml.v2.
> [INFO]	--> Fetching updates for golang.org/x/sys.
> [ERROR]	Update failed for github.com/fsouza/go-dockerclient: Unable to get repository
> [WARN]	Unable to checkout github.com/spf13/pflag
> [ERROR]	Update failed for github.com/spf13/pflag: Unable to get repository
> [WARN]	Unable to checkout github.com/kballard/go-shellquote
> [ERROR]	Update failed for github.com/kballard/go-shellquote: Unable to get repository
> [WARN]	Unable to checkout github.com/hashicorp/go-cleanhttp
> [ERROR]	Update failed for github.com/hashicorp/go-cleanhttp: Unable to get repository

Finally, it fails all together with:

> An Error has occurred
> [ERROR] Failed to execute task "deps:run": Exited with non-zero status code 2

**Comment by dnephin** [comment]
Thanks for the detailed error report.

The first `[WARN] Failed to load auth config` is safe to ignore because we're not loading any images from private repos. It's looking in `/` because is the `dnephin/dobi` image doesn't set `$HOME`, but we'd have to mount another volume to use them anyway.

The second set of errors looks like connection errors when downloading the go dependencies from github.  Does this problem persist? Maybe github was having issues at the time?

I just tried running the bootstrap locally and it worked for me. I don't know of any networking issues with Docker for Mac, but if you're able to hit github from the host, and you still get these connect errors, you could try adding `--net=host` to the `docker run` command to see if that fixes anything.

**Comment by deinspanjer** [comment]
Haven't noticed any github trouble, but I'll dig in a bit further.  If it is not reproducible for you, then it might be specific to either Docker for Mac or my environment.  I'll close this for the moment and open something more specific and relevant if I can track it down.
