### ISSUE TITLE
Unable to compile: undefined: tar.FormatPAX

### ISSUE THREAD

**Issue by cybe** [dnephin/dobi#134]
Since a couple of days I'm unable to compile dobi:

```
CGO_ENABLED=0 go get -u github.com/dnephin/dobi
# github.com/docker/cli/vendor/github.com/docker/docker/pkg/archive
/go/src/github.com/docker/cli/vendor/github.com/docker/docker/pkg/archive/archive.go:364:5: hdr.Format undefined (type *tar.Header has no field or method Format)
/go/src/github.com/docker/cli/vendor/github.com/docker/docker/pkg/archive/archive.go:364:15: undefined: tar.FormatPAX
/go/src/github.com/docker/cli/vendor/github.com/docker/docker/pkg/archive/archive.go:1166:7: hdr.Format undefined (type *tar.Header has no field or method Format)
/go/src/github.com/docker/cli/vendor/github.com/docker/docker/pkg/archive/archive.go:1166:17: undefined: tar.FormatPAX
```
Any hints?

**Comment by dnephin** [comment]
I guess a dependency made a backwards incompatible change. `dobi` uses [dep](https://github.com/golang/dep) to pin dependencies. So if you `dep ensure` to setup vendor it should build.

**Comment by cybe** [comment]
That was exactly it, thank you!

**Comment by theckman** [comment]
Someone just ran in to a similar on the Go Slack workspace. For anyone who finds this issue in the future, the issue was that the `Format` field was only added in go 1.10. If you're getting `hdr.Format undefined (type *tar.Header has no field or method Format)` make sure you're using Go 1.10 or newer.
