### ISSUE TITLE
Add ability to ignore/override .dockerignore

### ISSUE THREAD

**Issue by Fuco1** [dnephin/dobi#143]
I would like to have some auxiliary images built from a `./build` directory context but this is currently in my `.dockerignore` so that those files don't end up in the final images.

Is there any way to ignore the ignore file for the helper images?

**Comment by dnephin** [comment]
If I understand correctly the request is about specifcying different `.dockerignore` files for different image build tasks.

Right now I use a lot of the `docker/cli` and `docker/docker/client` code as libraries. I have been hoping that this feature would be supported upstream, but unfortunately it doesn't look like it will be: https://github.com/moby/moby/issues/12886

It's definitely possible that `dobi` could add support for this by forking the dependency and adding support. If someone is interested in contributing such a feature I should be able to help them out.

**Comment by dnephin** [comment]
I also generally keep my dockerfiles in a sub-directory, usually `dockerfiles/` or `dobifiles/`.

I never really do a `COPY . /app`, but it should still work to ignore that directory.

It is possible to use a Dockerfile from outside of the build context (or a dockerfile that is ignored in .dockerignore`). See this example:  https://github.com/dnephin/dobi/commit/940cfe1a79d8d2557a33a487280ba98794cf59e7

It should fail on the line that tries to `cat` the Dockerfile, because the file isn't there. It seems it still adds the directory that is ignored, I'm not sure why that is.

**Comment by Fuco1** [comment]
The concrete example is this `Dockerfile.env` inside `./build`.  

```
FROM alpine
RUN apk -U add bash

COPY build/env.sh /usr/bin/env.sh
COPY yarn.lock /code/yarn.lock
WORKDIR /code
CMD ["/usr/bin/env.sh"]
```

The dobi job was like this

```yaml
image=setup-env:
  image: setup-env
  context: .
  dockerfile: ./build/Dockerfile.env
```

Now the `COPY build/env.sh /usr/bin/env.sh` instruction won't work because that file is ignored (`.dockerignore` contains `./build` directory).

I've solved this by moving the context to `./build` and then mounting the yarn file as a volume instead.  So my particular issue was worked around, maybe I was just trying to do something silly.

**Comment by Fuco1** [comment]
I think we can close this issue.  Once this is supported upstream and there's a need for it we can add the feature to dobi, but it seems like it's not that necessary (as I've found a work around and nobody else asked for it).
