### ISSUE TITLE
Support a list of artifacts in the job resource

### ISSUE THREAD

**Issue by dnephin** [dnephin/dobi#17]
Instead of just a single artifact.

**Comment by deinspanjer** [comment]
I can take a look at implementing this some time next week unless someone needs it sooner.

What do you think about the following spec?

All forms of directory entries will always continue to staleCheck all files under the dir for simplicity and backward compatibility.

During the remove task, the array is traversed in reverse order.
The subdirectory spec is verbose, you have to keep repeating parent elements, but without that, we'd have to make some distinction between an artifact off of the root, and an artifact that is a child of the previous entry.  Even with that magic, you'd still end up having to repeat the full path for special cases such as [a, a/b, a/b/x, a/c, a/c/y]

- artifact: "filename" -- continues to work as is for backward compatibility
- artifact: "dir" -- rm the directory and everything under it.
- artifact: ["file"] -- identical to the plain string form
- artifact: ["dir"] -- identical to the plain string form
- artifact: ["dir/"] -- only rm the dir if it is empty.
- artifact: ["dir/", "dir/*"] -- rm everything under the dir, only rm the dir if it is empty.
- artifact: ["dir/*"] -- rm everything under the dir, don't rm the dir.
- artifact: ["dir/", "dir/subdir/*"] -- rm everything under subdir, only rm the dir if it is empty. (note, in this case, unless we make some assumptions, dir would never get removed since subdir is not explicitly an artifact.)
- artifact: ["dir/", "dir/subdir/file"] -- rm file, only rm the subdir if it is empty, only rm the dir if it is empty. (note, in this case, unless we make some assumptions, dir would never get removed since subdir is not explicitly an artifact.)
- artifact: ["dir/", "dir/subdir/", "dir/subdir/file"] -- rm file, only rm the subdir if it is empty, only rm the dir if it is empty.
- artifact: ["dir/", "dir/subdir/, "dir/subdir/*"] -- rm everything under subdir, only rm the subdir if it is empty, only rm the dir if it is empty.

**Comment by dnephin** [comment]
My thoughts:
* while we should continue to support `artifact: "file/dir name"` for now, we should print a deprecation warning so we can remove it in the future. With yaml a list of one item is just an extra two characters (`[item]`), so I've been opting to try and keep just a single type for each field.
* If any `rmdir` fails, it should probably print a warning
* I think both the "freshness check" and removal should use the same logic. Different logic for each could be really confusing. This might make it harder to keep things completely backwards compatible, but we are still "pre-1.0", and the breaking change would be "safer" (removes less), so it might not be the worst thing. One way to make this work might be to leave the `artifact` field as is (with a deprecation  warning) and add an `artifacts:` field  that supports the new logic. Setting both would be an error, and we could remove `artifact` in version 0.7.


We should also look at other fields that behaviour in a similar way. The only other one that I can see is `job.sources`. It should support the same globbing rules as `artifact`

**Comment by dnephin** [comment]
Fixed by #60

In the end this was just made to accept either a string, or list of strings, where the string is a glob pattern or exact path.
