### ISSUE TITLE
Need a way to specify a port mapping

### ISSUE THREAD

**Issue by deinspanjer** [dnephin/dobi#18]
If a job is created to be a "run" type task such as starting up a development web server, I don't believe there is currently any way to actually map that port to the host so you could do anything with the container.

Maybe rather than having a specific declaration just for ports, it would make sense to add a more generic "docker_args" declaration for jobs that would let the developer specify any particular extra args that should be passed through?

**Comment by deinspanjer** [comment]
I'll also just ask here, if you did have such a run task that was flagged as interactive and it ran until the user killed it, what would be the right way to be able to stop it without having dobi consider that to be an error / failure?

**Comment by dnephin** [comment]
>  don't believe there is currently any way to actually map that port to the host 

Correct, you can't do that directly yet, and I think it's something that should be added.

The way to do it for now is to use a `compose` resource, and a `docker-compose.yml`. You need to run the task as  `dobi resourcename:attach` to have it run in the foreground.

I think we should add a `ports:` field for `run` (which is renamed to `job` in master, I should probably do a release with that change included). 

> it would make sense to add a more generic "docker_args" declaration

I would rather it be more controlled, and we only add options as they are needed, for a few reasons:
* it's easier to document supported options when things are only supported explicitly
* there are many options that aren't going to make sense in the context of a build tool, and are more for production or "services".
* it's easier to reason about version compatibility with the docker API
* `dobi` uses the docker api, so the user would have to specify the options using the API name, which don't always match the cli flags, and often don't match in case, so it can be difficult for users to figure out what the correct option is. 


>  what would be the right way to be able to stop it without having dobi consider that to be an error

I was wondering that yesterday as well. Currently there is no way to accomplish that from `dobi`. I believe it's up to the application to handle `SIGINT` and exit with an exit status 0. That way `dobi` can consider it a "successful exit". We might be able to do something fancier from `dobi` (since the signal gets passed through), but I'm not sure it would be correct.

**Comment by deinspanjer** [comment]
> I was wondering that yesterday as well. Currently there is no way to accomplish that from dobi. I believe it's up to the application to handle SIGINT and exit with an exit status 0. That way dobi can consider it a "successful exit". We might be able to do something fancier from dobi (since the signal gets passed through), but I'm not sure it would be correct.

What about something like having dobi send a SIGTERM on the first Ctrl-C, and a SIGINT on the second?  That allows for the app to do a clean shutdown.  I think I've seen something else do that, but I can't recall the context.

**Comment by dnephin** [comment]
I think normally it's a `SIGINT` on the first and `SIGKILL` on the second. Applications can handle `SIGINT` the same way they handle `SIGTERM`. It seems strange to me that ctrl-c would translate to a `SIGTERM`, because normally it sends a `SIGINT`.

**Comment by deinspanjer** [comment]
sorry, yeah, was thinking about sigint and talking about sigterm cause I had ssh on the brain.

**Comment by cescoferraro** [comment]
This is the only reason I havent delete my docker-compose file yet!
Nice job @dnephin

**Comment by dnephin** [comment]
@cescoferraro awesome! I've put this issue into the next milestone. I've started some work on it in https://github.com/dnephin/dobi/tree/add-ports, but it's not quite done yet
