### ISSUE TITLE
Support new `docker build` features

### ISSUE THREAD

**Issue by philtay** [dnephin/dobi#79]
It would be great if the [image resource](https://dnephin.github.io/dobi/config.html#image) could support:

* `cache-from`
* `network`
* `target`

**Comment by dnephin** [comment]
I agree. Let me know if you're interested in submitting a PR to add them. 

Otherwise I will try to get to it this weekend

**Comment by philtay** [comment]
I don't have spare cycles right now, but you've just found a beta tester!

**Comment by dnephin** [comment]
I'm not seeing those flags supported in https://github.com/fsouza/go-dockerclient/ just yet, so we'll either need to submit a PR to add them, or wait a little bit.

**Comment by dnephin** [comment]
I've updated to description to include `target` as well, which was added in 17.05.

I don't think we should support `squash`. It's very likely going to be removed from docker because the new multi-stage builds provide a better way to create squashed images.

**Comment by dtshepherd** [comment]
I may try to pick this up if I find some spare time.  This issue is the only thing really holding me back from starting to use `dobi` for our project.  I need the new `network` attachment during building for a shared "secrets" container...

Right now, we're using `docker-compose` + a bunch of wrapper `bash` scripts.  `compose` is seriously lacking features for builds (multiple tags, pushing of those tags, boostrapping, build mounts, etc), hence the need for extra `bash` scripts...

I really think this project has some potential if more people start contributing!

**Comment by dtshepherd** [comment]
It looks like `network` (specified as `NetworkMode` in `go-dockerclient`) and `CacheFrom` are available in `go-dockerclient`, but `target` needs a PR.

**Comment by dnephin** [comment]
I'll release version 0.11 soon, which will have these fields added.
